export const FETCH_PLANETS_START = 'FETCH_PLANETS_START';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_FAIL = 'FETCH_PLANETS_FAIL';

export const FETCH_PLANETS_SCROLL_START = 'FETCH_PLANETS_SCROLL_START';
export const FETCH_PLANETS_SCROLL_SUCCESS = 'FETCH_PLANETS_SCROLL_SUCCESS';
export const FETCH_PLANETS_SCROLL_FAIL = 'FETCH_PLANETS_SCROLL_FAIL';

export const DETAIL_PLANETS_START = 'DETAIL_PLANETS_START';
export const DETAIL_PLANETS_SUCCESS = 'DETAIL_PLANETS_SUCCESS';
export const DETAIL_PLANETS_FAIL = 'DETAIL_PLANETS_FAIL';

export const SEARCH_PLANETS_START = 'SEARCH_PLANETS_START';
export const SEARCH_PLANETS_SUCCESS = 'SEARCH_PLANETS_SUCCESS';
export const SEARCH_PLANETS_FAIL = 'SEARCH_PLANETS_FAIL';